### ISSUE TITLE
library name not compatible with databinding

### ISSUE THREAD

**Issue by johnqinheracles** [ln-12/multiplatform-connectivity-status#2] opened 2022-01-12 22:33 UTC
library cannot find located when buildFeatures.databinding is truned on
![image](https://user-images.githubusercontent.com/55713102/149233648-bdb2012e-92c7-4b82-b802-191b6aeaea75.png)

**Comment by ln-12** [comment] 2022-01-13 13:29
Thanks for the report! I am not sure if that is a fault on my side or if kapt should be updated. Have you also filled an issue to the kapt team?

**Comment by davidoskky** [comment] 2022-08-21 18:21
This is a problem, hyphens are not allowed in java package names.
https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

**Comment by ln-12** [comment] 2022-08-22 10:25
I created a [new release](https://github.com/ln-12/multiplatform-connectivity-status/releases/tag/v1.2.0) which should fix this issue. Could you please update to version `com.github.ln-12:multiplatform-connectivity-status:1.2.0`, change the imports from`ln-12` to `ln_12` and verify that it is working for you?

**Comment by davidoskky** [comment] 2022-08-22 12:16
I confirm that the issue is fixed in the new release.

**Closed as completed** 2022-08-22 13:03 UTC
